# Generated by Django 4.2.7 on 2023-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_entidade_nif_alter_entidadedecontrato_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
