# Generated by Django 4.2.7 on 2023-11-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contrato_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morada',
            old_name='ativo_inativo',
            new_name='ativo',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='nif',
            field=models.CharField(max_length=9, verbose_name='NIF'),
        ),
    ]
